### PR TITLE
Check the next round is the correct round

### LINKED ISSUE #14: Wrong round served when backing node is 2 rounds behind
We try to be smart and we "wait" for the next round if you're requesting exactly the next round, except we don't actually check that the received round is correct, meaning if the underlying node is 2 rounds behind at the moment of the request, then we can serve the wrong beacon.

https://github.com/drand/http-relay/blob/60426725954061226113db100072262921fba75c/routes_handler.go#L78-L86

### PR DESCRIPTION
**Pull request by AnomalRoil**
Check the next round is the correct round

### CODE REVIEW

File: routes_handler.go [hunk 1]
```diff
@@ -84,6 +84,14 @@ func getBeacon(c *grpc.Client, r *http.Request, round uint64) (*grpc.HexBeacon,
 		}
 		// we use -1 to indicate no caching
 		nextTime = -1
+		if beacon.GetRound() != round {
+			beacon, err = c.GetBeacon(r.Context(), m, round)
```
Comment (GlacierWalrus) [inline routes_handler.go:88]: Is this the right thing to do? We're getting the wrong beacon, who says we'll get the next one on our next call? I feel this is a bit dangerous because if we have a bug where beacons aren't progressing for one node then this makes the relay recurse on this call stack right? Maybe I need to understand the code a bit better but quicker to ask since this is a semi urgent fix

File: go.mod [hunk 2]
```diff
@@ -3,25 +3,25 @@ module github.com/drand/http-relay
 go 1.22.10
 
 require (
-	github.com/drand/drand/v2 v2.0.4
-	github.com/go-chi/chi/v5 v5.2.0
+	github.com/drand/drand/v2 v2.1.0
```
Comment (GlacierWalrus) [inline go.mod:6]: Not a fan of doing unrelated lib upgrades during a hotfix

**Comment by GlacierWalrus** [comment]
I'm gonna stick an approve on this since you're the best person to judge design choices in this repo anyway, perhaps seek @CluEleSsUK 's input if you want a more authoritative approval

**Review by GlacierWalrus — APPROVED** [review]
Check comments before merging please, approving to expedite bug fix.

File: routes_handler.go (hunk 1 above)
Comment (AnomalRoil) [reply routes_handler.go:88]: This is initiating a call for that explicitly spelled `round` instead of optimistically trying to get the `Next` one.
Getting the next one is faster because it's using the streaming RPC endpoints, but cannot guarantee we're getting the right one. Calling here `c.GetBeacon` instead of `c.Next` as when we got the wrong one ensures at the backend level that we get the right one if we get one.

File: go.mod (hunk 2 above)
Comment (AnomalRoil) [reply go.mod:6]: https://github.com/drand/drand/compare/v2.0.4...v2.1.0
Should be fine
